### ISSUE TITLE
Cannot make recipe-less item, and cannot make multiple recipe-less items when using NONE format.

### ISSUE THREAD

**Issue by MinecraftAdmin** [NCBPFluffyBear/SlimeCustomizer#19]
## Description (Required)
So, im trying to add an item to SF using SlimeCustomizer, but without any recipe for it. With the help of Walshy, I was able to make an item using this format for the recipe for it:

```
  crafting-recipe-type: NONE
  crafting-recipe:
    1:
      type: NONE
      id: NONE
      amount: 0
    2:
      type: NONE
      id: NONE
      amount: 0
    3:
      type: NONE
      id: NONE
      amount: 0
    4:
      type: NONE
      id: NONE
      amount: 0
    5:
      type: NONE
      id: NONE
      amount: 0
    6:
      type: NONE
      id: NONE
      amount: 0
    7:
      type: NONE
      id: NONE
      amount: 0
    8:
      type: NONE
      id: NONE
      amount: 0
    9:
      type: NONE
      id: NONE
      amount: 0
```

This worked, but unfortunately I can only make 1 item that is recipe-less, when I add more items using this recipe, I get this error:

```[SlimeCustomizer] The crafting recipe for LUNAR_AXE1 is already being used for LUNAR_SWORD```

## Environment (Required)
![image](https://user-images.githubusercontent.com/1650123/131132671-c1e2849c-8295-439c-ace7-6e15d79cd6c5.png)
